# generated-from:a420b9b5f4bfcd0ca84a59bf34ec949efe4a54abb264fb854b633ba5d2eb667c DO NOT REMOVE, DO UPDATE

ACHWebViewer:
  Servers:
    Public:
      Bind:
        Address: ":8585"
    Admin:
      Bind:
        Address: ":9595"
